backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: "src/images/uploads"
public_folder: "/images/uploads"
collections:
  - label: "Page"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "src/index.md"
        fields:
          - { label: Title, name: title, widget: string }
